In [1]:
# GPU無効化
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [2]:
# データ処理のライブラリ
import numpy as np 
import pandas as pd

# データ可視化のライブラリ
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline 

# 機械学習ライブラリ scikit-learn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import fetch_openml

# 機械学習ライブラリ keras
import keras as ks
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import np_utils

In [3]:
import tensorflow as tf
print(tf.__version__) # 2.6.0

2.6.0


In [4]:
print(ks.__version__) # 2.6.0

2.6.0


In [5]:
# MNISTデータセットの読み込み
mnist = fetch_openml('MNIST_784', version=1)

# 特徴量とターゲットへ切り分け
X, y = mnist['data'], mnist['target']

# 訓練/テストセットへ分割
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=42) 

# 訓練データの最初の1万件のみへ縮小
# X_train = X_train[:10000]
# y_train = y_train[:10000]

# テストデータの最初の1万件のみへ縮小
# X_test = X_test[:10000]
# y_test = y_test[:10000]

# 正規化
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [6]:
# 特徴量データのサイズ
print(X_train.shape)
print(X_test.shape)

(56000, 784)
(14000, 784)


In [7]:
# Keras用にデータを整形
X_train = X_train.reshape(X_train.shape[0], 28, 28,1)
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)
print(X_train.shape)
print(X_test.shape)

(56000, 28, 28, 1)
(14000, 28, 28, 1)


In [8]:
# ターゲットデータの確認
print(y_train[0:5])
print(y_test[0:5])

['5' '4' '8' '0' '2']
['8' '4' '8' '7' '7']


In [9]:
# ターゲットデータをクラスベクトルへ変換
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

print(y_train[0:5])
print(y_test[0:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [10]:
# Sequentialモデル
model = Sequential()

In [11]:
# 入力層と畳み込み層
model.add(Conv2D(8, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1)))

In [12]:
# プール層
model.add(MaxPooling2D(pool_size=(2, 2)))

In [13]:
# ドロップアウト
model.add(Dropout(0.25))

In [14]:
# 全結合層
model.add(Flatten())
model.add(Dense(128, activation='relu'))

In [15]:
# 出力層
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 8)         80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 8)         0         
_________________________________________________________________
dropout (Dropout)            (None, 13, 13, 8)         0         
_________________________________________________________________
flatten (Flatten)            (None, 1352)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               173184    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 174,554
Trainable params: 174,554
Non-trainable params: 0
__________________________________________________

In [17]:
# モデル コンパイル
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [18]:
# 時間計測
import time
start_time = time.time()

In [19]:
# モデル訓練
model.fit(X_train, y_train, epochs=50)

Epoch 1/50
1750/1750 [==============================] - 7s 3ms/step - loss: 0.6032 - accuracy: 0.8165
Epoch 2/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.3119 - accuracy: 0.9047: 0s -
Epoch 3/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.2462 - accuracy: 0.9244: 
Epoch 4/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.2063 - accuracy: 0.9366: 0s - loss: 0.2073 - accuracy: 
Epoch 5/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.1789 - accuracy: 0.9454
Epoch 6/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.1589 - accuracy: 0.9504
Epoch 7/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.1427 - accuracy: 0.9566
Epoch 8/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.1340 - accuracy: 0.9579
Epoch 9/50
1750/1750 [==============================] - 5s 3ms/step - loss: 0.1229 - accuracy: 0.9609
Epoch 10/50
1750/1750 [===================

In [20]:
# 計測した結果を出力
tat_time = time.time() - start_time
print ("実行時間:{0}".format(tat_time) + "[秒]")

実行時間:268.4885687828064[秒]


In [21]:
# テストデータで推測結果を出力
cnn_pred = model.predict(X_test)

In [22]:
print(cnn_pred[0])

[7.2156024e-11 3.1388342e-12 8.8126899e-06 2.0176834e-05 6.9956662e-12
 9.9572794e-10 7.3062428e-15 7.1904643e-10 9.9997103e-01 5.8874932e-12]


In [23]:
# 推測結果をクラスラベルへ変換
y_pred_CNN = np.argmax(cnn_pred, axis=1)
y_test_CNN = np.argmax(y_test, axis=1)

In [24]:
print(confusion_matrix(y_test_CNN,y_pred_CNN))

[[1329    1    1    1    1    0    6    2    2    0]
 [   0 1586    2    3    2    0    0    4    3    0]
 [   0    2 1353    3    3    0    3    4   10    2]
 [   2    0    7 1399    0    7    0    5   11    2]
 [   1    0    0    0 1281    0    2    2    1    8]
 [   0    0    0    4    0 1257    8    0    4    0]
 [   1    0    0    0    4    1 1388    0    2    0]
 [   2    1    9    1    2    1    0 1480    2    5]
 [   1    1    6    2    2    1    2    5 1332    5]
 [   5    2    1    8   13    1    0    7    6 1377]]


In [25]:
print(accuracy_score(y_test_CNN,y_pred_CNN))

0.9844285714285714
